version: "3.1"

services:
  redmine:
#    image: redmine:4.1.1
    build:
      context: .
    restart: always
    ports:
    - 3000:3000
    volumes:
    - ../:/usr/src/redmine/plugins/redmine_extended_rest_api
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
      RAILS_ENV: test
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine