openapi: "3.0.0"
info:
  title: Redmine extended API overview
  version: 1.0.0
servers:
  - url: http://localhost:3000/extended_api
    description: local development instance
  - url: https://192.168.56.2/redmine/extended_api
    description: local development instance inside a CES
paths:
  /v1/settings:
    get:
      summary: List all available settings
      tags:
        - settings
      responses:
        '200':
          description: all available settings will be returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Settings"
              examples:
                simple:
                  $ref: "#/components/examples/settingsExample"
        '401':
          description: unauthorized access
    post:
      summary: Add or update one or more settings
      tags:
        - settings
      responses:
        204:
          description: the sent data is valid and was saved successfully
        400:
          description: the sent data contains invalid values and cannot be processed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        401:
          description: unauthorized access
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SettingsParam"

  /v1/workflows:
    get:
      summary: List all available workflow transitions
      tags:
        - workflows
      responses:
        '200':
          description: all available workflow transitions will be returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkflowTransitions"
        '401':
          description: unauthorized access
    patch:
      summary: Updates the given status transitions
      tags:
        - workflows
      responses:
        '204':
          description: update was successful
        '401':
          description: unauthorized access
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Transitions"
            examples:
              single:
                value:
                  {
                    "role_id": [ "1" ],
                    "tracker_id": [ "1" ],
                    "transitions": {
                      "123": { "always": "1" }
                    }
                  }
              multiple:
                value:
                  {
                    "role_id": [ "4" ],
                    "tracker_id": [ "23", "24" ],
                    "transitions": {
                      "12": { "always": "1", "author": "1", "assignee": "0" },
                      "123": { "always": "1", "author": "0", "assignee": "1" }
                    }
                  }

  /v1/issue_statuses:
    get:
      summary: a
      tags:
        - issue statuses
      responses:
        200:
          description: b
    post:
      summary: a
      tags:
        - issue statuses
      responses:
        200:
          description: b
    patch:
      summary: a
      tags:
        - issue statuses
      responses:
        200:
          description: b
    delete:
      summary: a
      tags:
        - issue statuses
      responses:
        200:
          description: b

  /v1/trackers:
    get:
      summary: a
      tags:
        - trackers
      responses:
        200:
          description: b
    post:
      summary: a
      tags:
        - trackers
      responses:
        200:
          description: b
    patch:
      summary: a
      tags:
        - trackers
      responses:
        200:
          description: b
    delete:
      summary: a
      tags:
        - trackers
      responses:
        200:
          description: b

components:
  examples:
    settingsExample:
      value:
        {
          "settings": [
            {
              "id": 1,
              "name": "app_title",
              "value": "MegaMine",
              "updated_on": "2021-01-26T17:21:45.517Z"
            },
            {
              "id": 2,
              "name": "rest_api_enabled",
              "value": "1",
              "updated_on": "2021-01-22T13:03:42.479Z"
            },
            {
              "id": 3,
              "name": "protocol",
              "value": "https",
              "updated_on": "2021-01-11T13:03:42.498Z"
            },
          ]
        }
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    SettingsParam:
      type: object
      properties:
        settings:
          description: all settings can be passed as simple key value pair inside the settings object
          minProperties: 1
          type: object
          additionalProperties:
            type: string
      example:
        settings:
          app_title: Megamine
          rest_api_enabled: "1"
    Settings:
      type: object
      properties:
        settings:
          type: array
          items:
            $ref: "#/components/schemas/Setting"
    Setting:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        value:
          type: string
        updated_on:
          type: string
    WorkflowTransitions:
      type: array
      items:
        $ref: "#/components/schemas/WorkflowTransition"
      example:
        [
          {
            "id": 11,
            "tracker_id": 1,
            "old_status_id": 3,
            "new_status_id": 1,
            "role_id": 1,
            "assignee": false,
            "author": false,
            "field_name": null,
            "rule": null
          },
          {
            "id": 12,
            "tracker_id": 1,
            "old_status_id": 3,
            "new_status_id": 2,
            "role_id": 1,
            "assignee": false,
            "author": false,
            "field_name": null,
            "rule": null
          }
        ]
    WorkflowTransition:
      type: object
      properties:
        id:
          type: integer
        tracker_id:
          type: integer
        old_status_id:
          type: integer
        role_id:
          type: integer
        assignee:
          type: string
        author:
          type: string
        field_name:
          type: string
        rule:
          type: string
      example:
        id: 11,
        tracker_id: 1
        old_status_id: 3
        new_status_id: 1
        role_id: 1
        assignee: false
        author: false
        field_name: null
        rule: null
    Transitions:
      type: object
      properties:
        role_id:
          type: array
          items:
            type: integer
        tracker_id:
          type: array
          items:
            type: integer
        transitions:
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              $ref: "#/components/schemas/Transition"
    Transition:
      type: object
      properties:
        always:
          type: string
          enum: [ "0", "1" ]
        author:
          type: string
          enum: [ "0", "1" ]
        assignee:
          type: string
          enum: [ "0", "1" ]
    Error:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
      example:
        {
          "errors": ["failed to save data", "item not found"]
        }

security:
  - basicAuth: []
