openapi: "3.0.0"
info:
  title: Redmine extended API overview
  version: 1.0.0
servers:
  - url: http://localhost:3000/extended_api
    description: local development instance
  - url: https://192.168.56.2/redmine/extended_api
    description: local development instance inside a CES
paths:
  /v1/settings:
    get:
      summary: List all available settings
      responses:
        '200':
          description: all available settings will be returned
          content:
            application/json:
              examples:
                simple:
                  value:
                    {
                      "settings": [
                        {
                          "id": 1,
                          "name": "app_title",
                          "value": "MegaMine",
                          "updated_on": "2021-01-26T17:21:45.517Z"
                        },
                        {
                          "id": 2,
                          "name": "rest_api_enabled",
                          "value": "1",
                          "updated_on": "2021-01-22T13:03:42.479Z"
                        },
                        {
                          "id": 3,
                          "name": "protocol",
                          "value": "https",
                          "updated_on": "2021-01-22T13:03:42.498Z"
                        },
                      ]
                    }
        '401':
          description: unauthorized access
    post:
      summary: Add or update one or more settings
      responses:
        204:
          description: the sent data is valid and was saved successfully
        400:
          description: the sent data contains invalid values and cannot be processed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        401:
          description: unauthorized access
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SettingsParam"
            examples:
              app_title:
                summary: add or update the app title setting
                value:
                  {
                    "settings": {
                      "app_title": "Megamine",
                      "default_language": "de"
                    }
                  }

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    SettingsParam:
      type: object
      properties:
        settings:
          description: all settings can be passed as simple key value pair inside the settings object
          minProperties: 1
          type: object
          properties:
            key:
              type: string
            value:
              type: string
    Settings:
      type: object
      properties:
        settings:
          type: array
          items:
            $ref: "#/components/schemas/Setting"
    Setting:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        value:
          type: string
        updated_on:
          type: string
    Error:
      type: object
      properties:
        errors:
          type: string

security:
  - basicAuth: []
